### ISSUE TITLE
Remove Boost dependency from MMCore

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/mmCoreAndDevices#260]
This is a housekeeping task that will simplify a bunch of things (build system improvement, pymmcore build, etc.). Most of what we use from Boost in MMCore can be replaced with `std` now that we are building with C++14. (Some device adapters may also be able to drop the Boost dependency, but that's for another time.)

---

A blanket replacement of `boost::` by `std::` can be done for the following items (#264):

- [x] Shared pointers
```
 357 boost::shared_ptr
  42 boost::make_shared
  13 boost::weak_ptr
  10 boost::static_pointer_cast
   4 boost::dynamic_pointer_cast
   2 boost::enable_shared_from_this
```

- [x] Unique pointer
```
   1 boost::unique_ptr (comment only)
```

- [x] Threading
```
  40 boost::mutex
  29 boost::lock_guard
  12 boost::thread
   3 boost::unique_lock
   3 boost::condition_variable
   2 boost::swap of thread (should use std with address-dependent lookup)
   1 boost::this_thread
```

- [x] Type-erased functions
```
   5 boost::function
   4 boost::bind
```
(`std::bind` can be simplified to lambdas.)

- [x] Vector (Boost was used to get `emplace_back`)
```
   3 boost::container::vector
```

---

These items have close replacements:

- [x] Foreach: replace with standard range-based `for` loop #265
```
   4 BOOST_FOREACH
```

- [x] Scoped array: our uses can be replaced with `std::vector` #272
```
   3 boost::scoped_array (Linux and Windows only)
```

- [x] Noncopyable: replace with `= delete` on copy constructor and copy assignment operator #269
```
   8 boost::noncopyable
```

- [x] Lexical cast (all our usage is to `std::string`): replace with `std::to_string`; `ToString` needs to be revamped a little #261
```
   4 boost::lexical_cast
```

- [x] Phoenix lambdas: replace with plain lambdas #263
These were used to emulate lambdas before we switched from C++03 (2cc31c9e0e36b65da41642af8be292cadbb6e6b0).
```
   2 boost::phoenix
```

- [x] String trim: use `std::string::erase` together with `std::string::find_last_not_of` #271
```
   1 boost::algorithm::trim (Windows only)
```

---

Finally, these need significant changes but can be replaced with `std` functions:

- [x] Date and time: these need to be rewritten using `std::chrono` functions.
    - [x] #274
    - [x] Depends on #273
```
   8 boost::posix_time::ptime
   6 boost::posix_time::microsec_clock
   2 boost::posix_time::time_facet
   1 boost::posix_time::to_iso_extended_string
   1 boost::posix_time::time_duration
   1 boost::posix_time::milliseconds
   2 boost::gregorian::date
```

---

- [x] Remove Boost from MMCore build scripts (VS/Autotools) #285 and micro-manager/micro-manager#1537
- [x] Remove Boost from pymmcore build scripts (pymmcore repo) micro-manager/pymmcore#69
