### ISSUE TITLE
MMTime woes

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/mmCoreAndDevices#273]
[`MM::MMTime`](https://github.com/micro-manager/mmCoreAndDevices/blob/172de90f682288741837dd8bc7182ed386566295/MMDevice/MMDevice.h#L97) is a data type we use in device adapters.

Although the data type (which consists of `long sec_` and `long uSec_`) is defined in MMDevice, getting the "current time" as an `MMTime` value is done through CoreCallback (`GetCurrentMMTime()`) (which turns out to be a good thing).

The [current implementation in MMCore](https://github.com/micro-manager/mmCoreAndDevices/blob/172de90f682288741837dd8bc7182ed386566295/MMCore/CoreUtils.h#L105-L117) (which hasn't changed since the switch from ACE to Boost, some time between 2008 and 2010) returns (according to my hopefully correct testing) seconds since 2000-01-01 00:00:00 UTC, plus the current time zone offset. That is, if you are on a UTC-500 timezone (US Central Daylight Time), the result is (number of seconds since 2000-01-01 UTC) minus 18000 (= 3600 x 5).

The vast majority, if not all, of existing usage of `MMTime` by device adapters is for the purpose of computing time deltas (i.e. measuring time between events). For such purposes, it makes more sense to use a steady (monotonic) clock (such as `std::chrono::steady_clock`) rather than the wall clock time (time mapped to calendar date and time and subject to adjustment).

The problems with the current implementation are:
- Because of the use of wall clock time, time deltas may be affected by system clock adjustments (probably a minor, or at least hard-to-notice, issue under common conditions). We should use a steady clock.
- Because of the local time offset being part of the value, time delta behavior may be completely broken if run while the time zone changes, e.g., for daylight saving time (a major issue, although obviously not encountered very often -- but who knows?). We should use UTC or a steady clock.
- The current behavior is hard to reproduce except by keeping the exact same Boost-based code.

A theoretical fix would be to use `std::chrono::steady_clock` everywhere in device adapters where time deltas need to be computed. But there is no mechanical conversion, and it is not practical to make such a change without the risk of introducing hard-to-test bugs into device adapters (not to mention the huge amount of manual work needed). So we need a fix that preserves `MMTime` and its relevant behavior.

The major difficulty in fixing `MMTime` is that, while I know that the vast majority of its use is for computing time deltas, we have no hard guarantee that it is not used to obtain the absolute date-time. Yet, we cannot fix it without at least changing the reference timepoint.

I'm thinking of doing the following, but let me know if anybody has other ideas or thoughts.

- [x] Review existing uses of `GetCurrentMMTime()` (818 public uses in 111 directories) to make sure that only time difference is being used.
- [x] Remove `g_Keyword_Metadata_StartTime` tag creation from all camera adapters (see next comment) #279
- [x] Fix negative time difference handling (see next comment) #281
- [ ] Change `GetCurrentMMTime()` to be unaffected by time zone and ensure it returns time relative to an epoch that is drastically different from 2000-01-01 (so that in the unlikely event that the absolute value is assumed to be since 2000-01-01, it will be noticeably, rather than subtly, wrong). #282
    - If we use `steady_clock`, which I think is best, then there is no fixed epoch (the internal time representation may change on every reboot, for example) -- which should be fine.
        - ~There is no guarantee that the whole seconds will fit in the `long` (32-bit on Windows) `sec_` field, but this can be worked around by recording our own zero timepoint at startup (or first call) and using relative values for `MMTime`.~
- [ ] Document `MMTime` as being suitable for time difference measurement only. Encourage the direct use of `std::chrono::time_point<std::chrono::steady_clock>` (which is much less error-prone) for time deltas in future device code. #282

**Comment by marktsuchida** [comment]
After reviewing current usage:

- A bunch of cameras (22 to be precise) do `md.put(MM::g_Keyword_Metadata_StartTime, CDeviceUtils::ConvertToString(sequenceStartTime_.getMsec()));` or similar where `sequenceStartTime_` comes from `GetCurrentMMTime()`. This means that the `"StartTime-ms"` metadata field is milliseconds since 2000, plus a time-zone-dependent offset. I'm not sure if anybody has ever used this metadata field, given that they would have had to read MMCore source code to know how to interpret it (and it would still be hard to get the offset right). It does not currently appear in micro-manager Java source. It also doesn't make sense to have per-frame metadata repeating the sequence start time. MDA summary metadata contains a `"StartTime"` (though that's not the same thing). Custom acquisition scripts can easily record the wall time before starting a sequence acquisition. See also an [old post](https://sourceforge.net/p/micro-manager/mailman/micro-manager-general/thread/CADHWJb6=dEiUYhy7JvqDmVLStqYreU9++VaWJBuvDu3gRG7Z9Q@mail.gmail.com/), which is the only reference I can find on the web except for even older (2011-2013) versions of acqEngine which had code to remove this tag from the metadata. I'd say we can remove this metadata tag from all cameras. Anybody opposed?

- PVCAM and PICAM sometimes log the absolute MMTime (without formatting it in human-readable form). This is for debugging and should not be affected by a change in the meaning of the absolute values.

- LeicaDMR and LeicaDMSTC do `changedTime_ = GetCurrentMMTime() - 5000000;`.
So we need to test if negative `MMTime` values work as expected (or prevent them from arising).
The reason `operator-()` works with a plain number on the right-hand side is the constructor `MMTime(double)` not being `explicit`. Maybe good to see if we can make it explicit and fix the few places that fail to compile.

**Comment by marktsuchida** [comment]
Not directly about this issue, but related to the danger of implicitly converting numbers to `MMTime` as pointed out above:
- [x] #277
- [ ] Add `explicit` to `MMTime` constructor

**Comment by marktsuchida** [comment]
Regarding negative values of `MMTime`:
- It looks like the existing behavior forces negative values to zero, except that if `sec_ >= 0` and `uSec_ < 0` it will store `sec_ = -1`; also, if constructed from a negative `double`, it will store negative `sec_` (clearly a bug).
- Most usage would benefit from making negative values work as expected. However, if the result is used as an argument to sleep, there could be trouble (because the argument will be interpreted as unsigned) if we change the behavior away from clamping to zero. Fortunately, on review of all uses of `CDeviceUtil::SleepMs()`, `Sleep()`, `sleep()`, `usleep()`, and `nanosleep()`, it does not appear that any derive their argument from an `MMTime` (at least in an obvious way).
- Whichever way (clamp to 0 or handle negative correctly) we fix, it is easier to store the internal value as a single 64-bit number (microseconds). But the `sec_` and `uSec_` fields are public. Fortunately, only 3 device adapters use these so they can be easily fixed.

The risk of introducing bugs by changing the behavior to handle negative values correctly is not absolutely zero, but I think it is sufficiently low that it is worth making the change (and any such cases are likely already partially broken). The risk of existing or future code having a bug under the current behavior is probably greater.

- [ ] Make data members private and fix PICAM, PVCAM, and XIMEACamera accordingly
- [ ] Add unit tests for correct handling of negative times by `MMTime`
- [ ] Change internal representation to `long long microseconds_;` and remove the incomplete clamp-to-zero code
